name: clippy-check
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - src/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - src/**

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
